baseURL = 'https://javi-tech-1971.github.io/GitHugo/'
languageCode = 'es-es'
title = 'Mi Sitio con Hextra'
theme = 'hextra'

[menu]
  [[menu.main]]
    name = "Home"
    pageRef = "/"
    weight = 10
  [[menu.main]]
    name = "Posts"
    pageRef = "/posts"
    weight = 20
